### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Riiquezz** [delete/estofadora#23]
Hey man, I need help with a situation.

I am messing with your application for implementation in another project.

I was wondering how this login system works.
Do you have pre-defined login data or how does it work?

How do I access the restricted area?

**Comment by Riiquezz** [comment]
-

**Comment by delete** [comment]
We already talked about it, but just to make it documented...

The user you'll use to log in, will be created after run the command `python manage.py createsuperuser`. At this point you can define what the username and password will be.
